/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdvertiseBox: typeof import('./components/AdvertiseBox.vue')['default']
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppMenu: typeof import('./components/app/AppMenu.vue')['default']
    AppProfile: typeof import('./components/app/AppProfile.vue')['default']
    AppSubmenu: typeof import('./components/app/AppSubmenu.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    Conditions: typeof import('./components/Conditions.vue')['default']
    FilterBar: typeof import('./components/FilterBar.vue')['default']
    Foo: typeof import('./components/basic/Foo.vue')['default']
    GridTable: typeof import('./components/GridTable.vue')['default']
    Hello: typeof import('./components/basic/Hello.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SapFilterbar: typeof import('./components/SapFilterbar.vue')['default']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    ValueHelp: typeof import('./components/ValueHelp.vue')['default']
    ValueHelpDialog: typeof import('./components/ValueHelpDialog.vue')['default']
    VariantManagement: typeof import('./components/VariantManagement.vue')['default']
  }
}
